const baseDeDatos =  [
    { id: 1, tipo: 'camisa', nombre: 'Camisa Mujer ', categoria: 'ropamujer', color: 'Azul', tamaño: 'M', tipoTela: 'Seda', precio: 39.99, img: 'img/camisas/azul/camisamujerazul.png'},
    { id: 2, tipo: 'camisa', nombre: 'Camisa Hombre ', categoria: 'ropahombre', color: 'Azul', tamaño: 'M', tipoTela: 'Algodón', precio: 19.99, img: 'img/camisas/azul/camisahombrelargazul.png'},
    { id: 3, tipo: 'camisa', nombre: 'Camisa Mujer ', categoria: 'ropamujer', color: 'Rojo', tamaño: 'S', tipoTela: 'Seda', precio: 39.99, img: 'img/camisas/rojo/camisamujerojo2.png' },
    { id: 4, tipo: 'camisa', nombre: 'Camiseta Hombre ', categoria: 'ropahombre', color: 'verde', tamaño: 'M', tipoTela: 'Algodón', precio: 19.99, img: 'img/camisas/verde/camisetahombreverde1.png'},
    { id: 5, tipo: 'camisa', nombre: 'Camisa Mujer ', categoria: 'ropamujer', color: 'Negro', tamaño: 'S', tipoTela: 'Seda', precio: 39.99, img: 'img/camisas/negro/camisamujernegra1.png'},
    { id: 6, tipo: 'camisa', nombre: 'Camisa Mujer ', categoria: 'ropamujer', color: 'Amarillo', tamaño: 'M', tipoTela: 'Algodón', precio: 19.99, img: 'img/camisas/amarillo/camisaamarillla1.png'},
    { id: 7, tipo: 'Pantalon', nombre: 'Pantalon Hombre ', categoria: 'ropahombre', color: 'Rojo', tamaño: 'S', tipoTela: 'Seda', precio: 39.99, img: 'img/pantalones/negro/pantalonhombrenegro1.png'},
    { id: 8, tipo: 'camisa',  nombre: 'Camisa Mujer ', categoria: 'ropamujer', color: 'Rojo', tamaño: 'M', tipoTela: 'Algodón', precio: 19.99, img: 'img/camisas/rojo/camisarojo2.png'},
    { id: 9, tipo: 'camisa', nombre: 'Camisa Mujer ', categoria: 'ropamujer', color: 'Rojo', tamaño: 'S', tipoTela: 'Seda', precio: 39.99, img: 'img/camisas/rojo/camisamujerrojo3.png' },
    { id: 10, tipo: 'Pantalon', nombre: 'Pantalon Hombre ', categoria: 'ropahombre', color: 'Morado', tamaño: 'M', tipoTela: 'Algodón', precio: 19.99, img: 'img/pantalones/morado/panthombremorado1.png'},
    { id: 11, tipo: 'camisa', nombre: 'Camisa Mujer ', categoria: 'ropamujer', color: 'Amarillo', tamaño: 'S', tipoTela: 'Seda', precio: 39.99, img: 'img/camisas/amarillo/camisamujeramarilla2.png' },
    { id: 12, tipo: 'Pantalon', nombre: 'Pantalon Hombre ', categoria: 'ropamujer', color: 'Verde', tamaño: 'M', tipoTela: 'Algodón', precio: 19.99, img: 'img/pantalones/verde/pantalonmujerverde1.png'},
    { id: 13, tipo: 'Pantalon', nombre: 'Pantalon Mujer ', categoria: 'ropamujer', color: 'Amarillo', tamaño: 'S', tipoTela: 'Seda', precio: 39.99, img: 'img/pantalones/amarillo/pantalonamarillomujer1.png'},
    { id: 14, tipo: 'camisa', nombre: 'Camisa Mujer ', categoria: 'ropamujer', color: 'Amarillo', tamaño: 'M', tipoTela: 'Algodón', precio: 19.99, img: 'img/camisas/amarillo/camisetamujer3.png'},
    { id: 15, tipo: 'camisa', nombre: 'Camiseta Mujer ', categoria: 'ropahombre', color: 'Negro', tamaño: 'S', tipoTela: 'Seda', precio: 39.99, img: 'img/camisas/negro/camisetahombrenegro1.png'},
    { id: 16, tipo: 'camisa', nombre: 'Camiseta Hombre ', categoria: 'ropahombre', color: 'Rojo', tamaño: 'M', tipoTela: 'Algodón', precio: 19.99, img: 'img/camisas/rojo/camisetahombrerojo1.png'},
    { id: 17, tipo: 'camisa', nombre: 'Camisa Mujer ', categoria: 'ropamujer', color: 'Negra', tamaño: 'S', tipoTela: 'Seda', precio: 39.99, img: 'img/camisas/negro/cmisanegramujer2.png' },
    { id: 18, tipo: 'camisa', nombre: 'Camiseta Hombre ', categoria: 'ropahombre', color: 'Amarillo', tamaño: 'M', tipoTela: 'Algodón', precio: 19.99, img: 'img/camisas/amarillo/camisetahombreamarilla1.png'},
    { id: 19, tipo: 'camisa', nombre: 'Camiseta Hombre ', categoria: 'ropahombre', color: 'Azul', tamaño: 'S', tipoTela: 'Seda', precio: 39.99, img: 'img/camisas/azul/camisetahombreazul1.png' },
    { id: 20, tipo: 'camisa', nombre: 'Camisa Mujer ', categoria: 'ropamujer', color: 'Verde', tamaño: 'M', tipoTela: 'Algodón', precio: 19.99, img: 'img/camisas/verde/camisamujerverde1.png'},
    { id: 21, tipo: 'camisa', nombre: 'Camiseta Hombre ', categoria: 'ropahombre', color: 'Blanco', tamaño: 'S', tipoTela: 'Seda', precio: 39.99, img: 'img/camisas/blanco/camisetablancohombre1.png' },
    { id: 22, tipo: 'Pantalon', nombre: 'Pantalon Mujer ', categoria: 'ropamujer', color: 'Rojo', tamaño: 'M', tipoTela: 'Algodón', precio: 19.99, img: 'img/pantalones/rojo/pantalonrojomujer1.png'},
    { id: 23, tipo: 'Pantalon', nombre: 'Pantalon Mujer ', categoria: 'ropamujer', color: 'Verde', tamaño: 'S', tipoTela: 'Seda', precio: 39.99, img: 'img/pantalones/verde/pantalonverdemujer2.png' },
    { id: 24, tipo: 'Pantalon', nombre: 'Pantalon Hombre ', categoria: 'ropahombre', color: 'Azul', tamaño: 'M', tipoTela: 'Algodón', precio: 19.99, img: 'img/pantalones/azul/pantalonhombreazul1.png'},
    { id: 25, tipo: 'Pantalon', nombre: 'Pantalon Hombre ', categoria: 'ropahombre', color: 'Amarillo', tamaño: 'S', tipoTela: 'Seda', precio: 39.99, img: 'img/pantalones/amarillo/pantalonhombreamarillo1.png' },
    { id: 26, tipo: 'Pantalon', nombre: 'Pantalon Hombre ', categoria: 'ropahombre', color: 'Verde', tamaño: 'M', tipoTela: 'Algodón', precio: 19.99, img: 'img/pantalones/verde/pantalonhombreverde1.png'},
    { id: 27, tipo: 'Pantalon', nombre: 'Pantalon Mujer ', categoria: 'ropamujer', color: 'Blanco', tamaño: 'S', tipoTela: 'Seda', precio: 39.99, img: 'img/pantalones/blanco/pantalonmujerblanco1.png' },
    { id: 28, tipo: 'Pantalon', nombre: 'Pantalon Hombre ', categoria: 'ropahombre', color: 'Verde', tamaño: 'M', tipoTela: 'Algodón', precio: 19.99, img: 'img/pantalones/verde/pantalonverdehombre2.png'},
    { id: 29, tipo: 'camisa', nombre: 'Camisa Mujer ', categoria: 'ropamujer', color: 'Blanco', tamaño: 'S', tipoTela: 'Seda', precio: 39.99, img: 'img/camisas/blanco/camisalargablancamujer2.png' },
    { id: 30, tipo: 'Pantalon', nombre: 'Pantalon Hombre ', categoria: 'ropahombre', color: 'Azul', tamaño: 'M', tipoTela: 'Algodón', precio: 19.99, img: 'img/pantalones/azul/pantalonhombreazul2.png'},
    { id: 31, tipo: 'Pantalon', nombre: 'Pantalon Mujer ', categoria: 'ropamujer', color: 'Azul', tamaño: 'S', tipoTela: 'Seda', precio: 39.99, img: 'img/pantalones/azul/pantalonmujerazul1.png' },
    { id: 32, tipo: 'Pantalon', nombre: 'Pantalon Hombre ', categoria: 'ropahombre', color: 'Azul', tamaño: 'M', tipoTela: 'Algodón', precio: 19.99, img: 'img/pantalones/azul/pantalonhombreazul3.png'},
    { id: 33, tipo: 'Pantalon', nombre: 'Pantalon Mujer ', categoria: 'ropamujer', color: 'Negro', tamaño: 'S', tipoTela: 'Seda', precio: 39.99, img: 'img/pantalones/negro/pantalonmujernegro1.png' },
    { id: 34, tipo: 'Pantalon', nombre: 'Pantalon Hombre ', categoria: 'ropamujer', color: 'Cafe', tamaño: 'M', tipoTela: 'Algodón', precio: 19.99, img: 'img/pantalones/cafe/pantalonmujercafe1.png'},
    { id: 35, tipo: 'Pantalon', nombre: 'Pantalon Hombre ', categoria: 'ropahombre', color: 'Cafe', tamaño: 'S', tipoTela: 'Seda', precio: 39.99, img: 'img/pantalones/cafe/pantalonhombrecafe1.png' },
    { id: 36, tipo: 'Pantalon', nombre: 'Pantalon Hombre ', categoria: 'ropahombre', color: 'Naranja', tamaño: 'M', tipoTela: 'Algodón', precio: 19.99, img: 'img/pantalones/naranja/pantalonaranjahombre1.png'},
    { id: 37, tipo: 'Pantalon', nombre: 'Pantalon Mujer ', categoria: 'ropamujer', color: 'Naranja', tamaño: 'S', tipoTela: 'Seda', precio: 39.99, img: 'img/pantalones/naranja/pantalonaranjamujer1.png' },
    { id: 38, tipo: 'Pantalon', nombre: 'Pantalon Hombre ', categoria: 'ropahombre', color: 'Gris', tamaño: 'M', tipoTela: 'Algodón', precio: 19.99, img: 'img/pantalones/gris/pantalonhombregris1.png'},
    { id: 39, tipo: 'Pantalon', nombre: 'Pantalon Mujer ', categoria: 'ropamujer', color: 'Gris', tamaño: 'S', tipoTela: 'Seda', precio: 39.99, img: 'img/pantalones/gris/pantalongrismujer1.png' },
    { id: 40, tipo: 'Camiseta', nombre: 'Camiseta Hombre ', categoria: 'ropahombre', color: 'Naranja', tamaño: 'M', tipoTela: 'Algodón', precio: 19.99, img: 'img/camisas/naranja/camisetahombrenaranja1.png'},
    { id: 41, tipo: 'camisa', nombre: 'Camisa Mujer ', categoria: 'ropamujer', color: 'Naranja', tamaño: 'S', tipoTela: 'Seda', precio: 39.99, img: 'img/camisas/naranja/camisanaranjamujer1.png' },
    { id: 42, tipo: 'camisa', nombre: 'Camiseta Hombre ', categoria: 'ropahombre', color: 'Verde', tamaño: 'M', tipoTela: 'Algodón', precio: 19.99, img: 'img/camisas/verde/camisetahombreverde2.png'},
    { id: 43, tipo: 'camisa', nombre: 'Camiseta Mujer ', categoria: 'ropamujer', color: 'Morado', tamaño: 'S', tipoTela: 'Seda', precio: 39.99, img: 'img/camisas/morado/cmisetamujermorado1.png' },
    { id: 44, tipo: 'camisa', nombre: 'Camisa Hombre ', categoria: 'ropahombre', color: 'Morado', tamaño: 'M', tipoTela: 'Algodón', precio: 19.99, img: 'img/camisas/morado/camisalargahombremorado1.png'},
    { id: 45, tipo: 'camisa', nombre: 'Camiseta Mujer ', categoria: 'ropamujer', color: 'Negro', tamaño: 'S', tipoTela: 'Seda', precio: 39.99, img: 'img/camisas/negro/cmisetamujernegro4.png' },
    { id: 46, tipo: 'camisa', nombre: 'Camiseta Hombre ', categoria: 'ropahombre', color: 'Negro', tamaño: 'M', tipoTela: 'Algodón', precio: 19.99, img: 'img/camisas/negro/camisetahombrenegro2.png'},
    { id: 47, tipo: 'camisa', nombre: 'Vestido Mujer ', categoria: 'ropamujer', color: 'Cafe', tamaño: 'S', tipoTela: 'Seda', precio: 39.99, img: 'img/camisas/cafe/camisetamujercafe1.png' },
    { id: 48, tipo: 'camisa', nombre: 'Camiseta Hombre ', categoria: 'ropahombre', color: 'Morado', tamaño: 'M', tipoTela: 'Algodón', precio: 19.99, img: 'img/camisas/morado/camisetahombremorado2.png'},
    { id: 49, tipo: 'Pantalon', nombre: 'Pantalon Mujer ', categoria: 'ropamujer', color: 'Azul', tamaño: 'S', tipoTela: 'Seda', precio: 39.99, img: 'img/pantalones/azul/pantalonazulmujer2.png' },
    { id: 50, tipo: 'Pantalon', nombre: 'Pantalon Hombre ', categoria: 'ropahombre', color: 'Rojo', tamaño: 'M', tipoTela: 'Algodón', precio: 19.99, img: 'img/pantalones/rojo/pantalonhombrerojo1.png'},
];